---

- name: Add user 'ansible' with a bash shell, appending the group 'wheel'
  ansible.builtin.user:
    name: "ansible"
    shell: "/bin/bash"
    groups: "wheel"
    append: yes
    update_password: always
    password: "{{ ansiblepwd|password_hash('sha512') }}"

- name: Create and/or recursively change ownership of user ansible's .ssh directory
  ansible.builtin.file:
    path: ~ansible/.ssh
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Generate an OpenSSH keypair for user 'ansible' with the default values (521 bits, ed25519)
  community.crypto.openssh_keypair:
    path: ~ansible/.ssh/id_ed25519
    type: ed25519
    owner: ansible
    group: ansible

- name: Set up multiple authorized keys for user 'ansible'
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: '{{ pubkey_item }}'
  with_file:
    - public_keys/apollo-tycho-id_ed25519.pub
    - public_keys/freya-tycho-id_ed25519.pub
    - public_keys/M2729-doctert-id_rsa.pub
    - public_keys/heimdall-ansible-id_ed25519.pub
  loop_control:
    loop_var: pubkey_item

- name: Generate an OpenSSH keypair for user 'root' with the default values (521 bits, ed25519)
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    owner: root
    group: root

- name: Make sure public keys are set present at user 'root'
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ pubkey_item }}"
  with_file:
    - public_keys/apollo-tycho-id_ed25519.pub
    - public_keys/freya-tycho-id_ed25519.pub
    - public_keys/M2729-doctert-id_rsa.pub
    - public_keys/heimdall-ansible-id_ed25519.pub
  loop_control:
    loop_var: pubkey_item

- name: Ensure root ssh login is not possible
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"

- name: Ensure ssh login with key is possible
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication'
    line: "PubkeyAuthentication yes"

- name: Set password for user 'root'
  ansible.builtin.user:
    name: root
    update_password: always
    password: "{{ rootpwd|password_hash('sha512') }}"

...
